apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-prod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-node-prod
  template:
    metadata:
      labels:
        app: hello-node-prod
    spec:
      containers:
      - name: hello-node-prod
        image: anonja/nodejs-api:v2
        env:
        - name: ENV1
          valueFrom:
            configMapKeyRef:
              name: hello-node-configmap
              key: greeting
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: hello-node-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: hello-node-secret
              key: password
        ports:
        - containerPort: 80