apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-prod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-node-prod
  template:
    metadata:
      labels:
        app: hello-node-prod
    spec:
      containers:
      - name: hello-node-prod
        image: anonja/nodejs-api:v2
        ports:
        - containerPort: 80