apiVersion: v1
kind: Service
metadata:
  name: hello-node-prod-service
  labels:
    app: hello-node-prod
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-node-prod