apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-node
  name: hello-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-node
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - image: anonja/nodejs-api:f4be80
          name: hello-node
          resources: {}
status: {}
