name: "production"

on:
  push:
    branches: [ "main" ]

jobs:
    retag:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        defaults:
            run:
              working-directory: ./hand-on # Here the path to the folder where package-lock.json is located.
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Get Image Name & Tag
          id: get_image_name
          uses: mikefarah/yq@master
          with:
            cmd: yq -r '.spec.template.spec.containers.[0].image' hand-on/manifest/develop/deployment.yaml