name: "production"

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hand-on # Here the path to the folder where package-lock.json is located.
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Retag Container Image
        id: retag
        env:
          APP_IMAGE: ${{ vars.APP_IMAGE }}
        working-directory: ./manifest/dev
        run: |
          IMAGE_SOURCE=$(yq eval '.spec.template.spec.containers[0].image' deployment.yaml)
          docker pull $IMAGE_SOURCE

          IMAGE_TOCHANGE=${APP_IMAGE}:${GITHUB_RUN_ID}
          echo "IMAGE_TOCHANGE=${IMAGE_TOCHANGE}" >> $GITHUB_OUTPUT

          docker tag $IMAGE_SOURCE $IMAGE_TOCHANGE
          docker push $IMAGE_TOCHANGE